export const FETCH_CART_ITEMS_START = "FETCH CART ITEMS ";
export const FETCH_CART_ITEMS_SUCCESS = "FETCH CART ITEMS SUCESS";
export const FETCH_CART_ITEMS_FAILED = "FETCH CART ITEMS FAILED";

export const ADD_TO_CART_START = "ADD TO CART START";
export const ADD_TO_CART_SUCCESS = "ADD TO CART SUCCESS";
export const ADD_TO_CART_FAILED = "ADD TO CART FAILED";

// "ADD TO CART LOCAL";
// "ADD TO CART SERVER SUCCESS";
// "ADD TO CART SERVER FAILED";

export const CLEAR_CART = "CLEAR CART";

export const UPDATE_CART_START = "UPADATE CART START";
export const UPDATE_CART_SUCCESS = "UPADATE CART SUCCESS";
export const UPDATE_CART_FAILED = "UPADATE CART FAILED";

export const CHANGE_QUANTITY = "CHANGE QUANTITY";
export const REMOVE_FROM_CART = "REMOVE FROM CART";

export const FETCH_FOOD_ITEMS_START = "START FETCH_FOOD_ITEMS";
export const FETCH_FOOD_ITEMS_SUCCESS = "FECTH FOOD ITEMS SUCCESS";
export const FETCH_FOOD_ITEMS_FAILED = "FECTH FOOD ITEMS FAILED";

export const LOGIN_START = "LOGIN START";
export const LOGIN_SUCCESS = "LOGIN SUCCESS";
export const LOGIN_FAILED = "LOGIN FAILED";

export const LOGOUT_START = "LOGOUT START";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";
export const LOGOUT_FAILED = "LOGOUT FAILED";

export const GET_USER_START = "GET USER START";
export const SET_USER = "SET USER";
export const GET_USER_FAILED = "GET USER FAILED";

export const FETCH_ORDERS_START = "FETCH ORDERS START";
export const FETCH_ORDERS_SUCCESS = "FETCH ORDERS SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH ORDERS FAILED";

export const PLACE_ORDER_START = "PLACE ORDER START";
export const PLACE_ORDER_SUCCESS = "PLACE ORDER SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE ORDER FAILED";

export const RESET_PLACED_SUCCESSFULLY = "RESET PLACED SUCCESSFULLY";

export const FIRST_TIME_APP_LOADED = "FIRST TIME APP LOADED";
