# Generated by Django 3.0.5 on 2020-05-30 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='food-images')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('GY', 'Gym Food'), ('BR', 'Breakfast')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=500, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=500, null=True)),
                ('paymentMethod', models.CharField(blank=True, choices=[('C', 'Cash On Delivery'), ('P', 'Paytm')], max_length=1, null=True)),
                ('pincode', models.CharField(blank=True, max_length=8, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('C', 'Cooking'), ('W', 'Ready'), ('IT', 'In-transit'), ('D', 'Delivered'), ('CBU', 'Canceled by User'), ('CBA', 'Canceled by Admin')], max_length=3)),
                ('items', models.ManyToManyField(to='food.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.FoodItem'),
        ),
    ]
