# Generated by Django 3.0.5 on 2020-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('C', 'Cooking'), ('W', 'Ready'), ('IT', 'In-transit'), ('D', 'Delivered'), ('CBU', 'Canceled by User'), ('CBA', 'Canceled by Admin')], max_length=3, null=True),
        ),
    ]
